sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=typing

cache:
  directories:
    - $HOME/.cache/pip
language: python
install: "pip install tox"
script: tox
